# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/jchoward/miniconda/envs/newriver_psi4/bin/cmake

# The command to remove a file.
RM = /home/jchoward/miniconda/envs/newriver_psi4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jchoward/newriver/rhf_dlmg2b

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jchoward/newriver/rhf_dlmg2b

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/jchoward/miniconda/envs/newriver_psi4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/jchoward/miniconda/envs/newriver_psi4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jchoward/newriver/rhf_dlmg2b/CMakeFiles /home/jchoward/newriver/rhf_dlmg2b/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jchoward/newriver/rhf_dlmg2b/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rhf_dlmg2b

# Build rule for target.
rhf_dlmg2b: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rhf_dlmg2b
.PHONY : rhf_dlmg2b

# fast build rule for target.
rhf_dlmg2b/fast:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/build
.PHONY : rhf_dlmg2b/fast

myelst.o: myelst.cc.o

.PHONY : myelst.o

# target to build an object file
myelst.cc.o:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/myelst.cc.o
.PHONY : myelst.cc.o

myelst.i: myelst.cc.i

.PHONY : myelst.i

# target to preprocess a source file
myelst.cc.i:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/myelst.cc.i
.PHONY : myelst.cc.i

myelst.s: myelst.cc.s

.PHONY : myelst.s

# target to generate assembly for a file
myelst.cc.s:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/myelst.cc.s
.PHONY : myelst.cc.s

plugin.o: plugin.cc.o

.PHONY : plugin.o

# target to build an object file
plugin.cc.o:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/plugin.cc.o
.PHONY : plugin.cc.o

plugin.i: plugin.cc.i

.PHONY : plugin.i

# target to preprocess a source file
plugin.cc.i:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/plugin.cc.i
.PHONY : plugin.cc.i

plugin.s: plugin.cc.s

.PHONY : plugin.s

# target to generate assembly for a file
plugin.cc.s:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/plugin.cc.s
.PHONY : plugin.cc.s

rhfdlmg2b.o: rhfdlmg2b.cc.o

.PHONY : rhfdlmg2b.o

# target to build an object file
rhfdlmg2b.cc.o:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/rhfdlmg2b.cc.o
.PHONY : rhfdlmg2b.cc.o

rhfdlmg2b.i: rhfdlmg2b.cc.i

.PHONY : rhfdlmg2b.i

# target to preprocess a source file
rhfdlmg2b.cc.i:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/rhfdlmg2b.cc.i
.PHONY : rhfdlmg2b.cc.i

rhfdlmg2b.s: rhfdlmg2b.cc.s

.PHONY : rhfdlmg2b.s

# target to generate assembly for a file
rhfdlmg2b.cc.s:
	$(MAKE) -f CMakeFiles/rhf_dlmg2b.dir/build.make CMakeFiles/rhf_dlmg2b.dir/rhfdlmg2b.cc.s
.PHONY : rhfdlmg2b.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... rhf_dlmg2b"
	@echo "... myelst.o"
	@echo "... myelst.i"
	@echo "... myelst.s"
	@echo "... plugin.o"
	@echo "... plugin.i"
	@echo "... plugin.s"
	@echo "... rhfdlmg2b.o"
	@echo "... rhfdlmg2b.i"
	@echo "... rhfdlmg2b.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

